# Generated by Django 5.0.3 on 2024-04-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_usercart_product_alter_usercart_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='user',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
