# Generated by Django 5.0.3 on 2024-04-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_usercart_product_alter_usercart_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
