# Generated by Django 5.0.3 on 2024-04-13 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_usercart_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('building_number', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('user_cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.usercart')),
            ],
        ),
    ]
