# Generated by Django 5.0.3 on 2024-04-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_orders',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
