# Generated by Django 5.0.3 on 2024-04-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_product_total_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
