# Generated by Django 5.0.3 on 2024-04-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_orderdetails_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
