# Generated by Django 5.0.3 on 2024-04-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_usercart_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='date_delivered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
