# Generated by Django 5.0.3 on 2024-04-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_review_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_star',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
