# Generated by Django 5.0.3 on 2024-04-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_product_total_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='orderId',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
